# Generated by Django 3.2.5 on 2021-07-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galary',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='galary',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
