# Generated by Django 3.2.5 on 2021-07-20 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Causes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('total', models.FloatField(blank=True, null=True)),
                ('causes_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('causes_date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
