# Generated by Django 3.2.5 on 2021-07-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causes',
            name='causes_date',
        ),
        migrations.AddField(
            model_name='causes',
            name='current',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
