# Generated by Django 3.2.5 on 2021-07-20 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('blog_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('blog_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
