# Generated by Django 3.2.5 on 2021-07-20 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
